# Web applications

[webapps.discord]
name = "Discord"
url = "https://discord.com/app"
icon = "discord"

[webapps.twitch]
name = "Twitch"
url = "https://www.twitch.tv"
icon = "gnome-twitch"

[webapps.youtube]
name = "YouTube"
url = "https://www.youtube.com/feed/subscriptions"
icon = "youtube"

[webapps.github]
name = "GitHub"
url = "https://github.com"
icon = "github"

