[colors]
base    = "#1a1b26"
surface = "#24283b"
overlay = "#414868"
text    = "#9aa5ce"
muted   = "#565f89"

primary   = "#73daca"
secondary = "#7aa2f7"
accent    = "#bb9af7"

success = "#9ece6a"
error   = "#f7768e"
warning = "#e0af68"
info    = "#cfc9c2"

